### PR TITLE
Add data attributes

### PR DESCRIPTION
**Pull request by Xiot**
Adds a new `dataAttributes` property to the config.
This optional parameter will allows the selected variants to be added to the dom as a `data-*` attribute.

```javascript
const Button = classed('button', {
  variants: { color: { blue: 'bg-blue-100' } },
  dataAttributes: ['color']
})
```

With the inclusion of the `dataAttributes`, this jsx
```jsx
<Button color="blue" />
```
will produce
```html
<button data-color="blue" />
```

Addresses: https://github.com/sannajammeh/tw-classed/issues/104

### CODE REVIEW

**Comment by Xiot** [comment]
I still need to type it properly, but I wanted to get your take on the approach first.
Let me know what you think.

**Comment by sannajammeh** [comment]
Well done!

Havent had time to recipe this just yet, but I'll get to it this week.

**Comment by sannajammeh** [comment]
I added the types for this to work in your branch, however I cant push it yet due to missing permissions. Could you invite me to your branch?

**Comment by Xiot** [comment]
> I added the types for this to work in your fork, however I cant push it yet due to missing permissions. Could you invite me to your fork?

Just added you.

**Comment by sannajammeh** [comment]
Pointing this to Canary for pre-release :) Thanks for the work, I appreciate it!

**Pull request merged**
